[package]
edition = "2021"
name = "intercode_rust"
version = "0.1.0"

[profile.release]
debug = 1

[workspace]
members = [
  "./crates/intercode_entities",
  "./crates/intercode_graphql",
  "./crates/intercode_inflector",
  "./crates/intercode_liquid",
  "./crates/intercode_timespan",
  "./crates/lazy_liquid_value_view",
  "./crates/lazy_liquid_value_view_derive",
]

[features]
dhat-heap = ["dep:dhat"] # if you are doing heap profiling
flamegraph = ["dep:tracing-flame"]

[dependencies]
async-graphql = {version = "~4.0.5", features = ["tracing", "dataloader", "chrono"]}
async-graphql-axum = "4.0.10"
async-graphql-value = "~4.0.5"
axum = "0.5.13"
chrono = "0.4"
chrono-tz = "0.6"
clap = {version = "3.2.17", features = ["derive", "cargo"]}
ctrlc = "3.2.2"
dhat = {version = "0.3.0", optional = true}
dotenv = "0.15.0"
futures = "0.3.21"
html-escape = "0.2.11"
http = "0.2.8"
hyper = "0.14.20"
i18n-embed = {version = "0.13", features = ["fluent-system"]}
i18n-embed-fl = "0.6"
intercode_entities = {path = "./crates/intercode_entities"}
intercode_graphql = {path = "./crates/intercode_graphql"}
intercode_inflector = {path = "./crates/intercode_inflector"}
intercode_liquid = {path = "./crates/intercode_liquid"}
intercode_timespan = {path = "./crates/intercode_timespan"}
lazy_liquid_value_view = {path = "./crates/lazy_liquid_value_view"}
liquid = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}
liquid-core = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}
md5 = "*"
once_cell = "1.13.0"
opentelemetry = {version = "0.17.0", features = ["rt-tokio"]}
opentelemetry-otlp = {version = "0.10.0", features = ["tls-roots"]}
pulldown-cmark = "0.9.1"
quote = "1.0.20"
regex = "*"
rust-embed = "6"
rustls-pemfile = "1.0.1"
sea-orm = {version = "^0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"]}
serde = "1.0"
serde_json = "1.0"
syn = "1.0.98"
tls-listener = {version = "0.5.1", features = ["rustls", "tokio-net"]}
tokio = {version = "~1.20.1", features = ["rt-multi-thread", "macros", "signal", "tracing"]}
tokio-rustls = "0.23.4"
tonic = "0.6.2"
tower = {version = "0.4.13", features = ["limit", "make"]}
tower-http = {version = "0.3.4", features = ["catch-panic", "compression-br", "compression-deflate", "compression-gzip", "trace"]}
tracing = "0.1.35"
tracing-flame = {version = "0.2.0", optional = true}
tracing-opentelemetry = "0.17.4"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
typed-arena = "2.0.1"
unic-langid = "0.9"
url = "*"
