[package]
edition = "2021"
name = "intercode_rust"
version = "0.1.0"

[profile.release]
debug = 1

[features]
dhat-heap = ["dep:dhat"] # if you are doing heap profiling

[dependencies]
async-graphql = {version = "~3.0.38", features = ["tracing", "dataloader", "chrono"]}
async-graphql-value = "~3.0.38"
async-graphql-warp = "~3.0.38"
chrono = "0.4"
chrono-tz = "0.6"
clap = {version = "3.2.4", features = ["derive", "cargo"]}
ctrlc = "3.2.2"
dhat = {version = "0.3.0", optional = true}
dotenv = "0.15.0"
html-escape = "0.2.11"
hyper = "0.14.19"
i18n-embed = {version = "0.13", features = ["fluent-system"]}
i18n-embed-fl = "0.6"
intercode_entities = {path = "./crates/intercode_entities"}
intercode_graphql = {path = "./crates/intercode_graphql"}
intercode_inflector = {path = "./crates/intercode_inflector"}
intercode_liquid = {path = "./crates/intercode_liquid"}
liquid = "0.26.0"
liquid-core = "0.26.0"
md5 = "*"
pulldown-cmark = "0.9.1"
quote = "1.0.18"
regex = "*"
rust-embed = "6"
rustls-pemfile = "1.0.0"
sea-orm = {version = "^0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"]}
serde = "1.0"
serde_json = "1.0"
syn = "1.0.92"
tls-listener = {version = "0.5.1", features = ["rustls", "tokio-net"]}
tokio = {version = "~1.18.0", features = ["rt-multi-thread", "macros", "signal"]}
tokio-rustls = "0.23.4"
tower = {version = "0.4.12", features = ["limit", "make"]}
tower-http = {version = "0.3.4", features = ["compression-br", "compression-deflate", "compression-gzip"]}
tracing = "0.1.34"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
unic-langid = "0.9"
url = "*"
warp = {version = "~0.3.2"}
