[package]
edition = "2021"
name = "intercode_rust"
version = "0.1.0"

[profile.release]
debug = 1

[workspace]
members = [
  "./crates/intercode_entities",
  "./crates/intercode_graphql",
  "./crates/intercode_inflector",
  "./crates/intercode_liquid",
  "./crates/intercode_policies",
  "./crates/intercode_timespan",
  "./crates/lazy_liquid_value_view",
  "./crates/lazy_liquid_value_view_derive",
  "./crates/seawater",
  "./crates/seawater_derive",
]

[workspace.dependencies]
liquid = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}
liquid-core = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}

[features]
dhat-heap = ["dep:dhat"] # if you are doing heap profiling
flamegraph = ["dep:tracing-flame"]
tokio-console = ["dep:console-subscriber", "tokio/full", "tokio/tracing"]

[dependencies]
anyhow = "1.0.66"
async-graphql = {version = "~4.0.5", features = ["tracing", "dataloader", "chrono"]}
async-graphql-axum = "4.0.10"
async-graphql-value = "~4.0.5"
async-stripe = {version = "0.15.0", default-features = false, features = ["runtime-tokio-hyper-rustls", "checkout", "chrono", "connect", "webhook-events"]}
axum = {version = "0.5.16", features = ["multipart"]}
axum-extra = {version = "0.3.7", features = ["cookie"]}
axum-sea-orm-tx = {version = "0.1.0", git = "https://github.com/nbudin/axum-sea-orm-tx.git"}
axum-sessions = "0.3.1"
base64 = "0.13.0"
bcrypt = "0.13.0"
bumpalo-herd = "0.1.2"
chrono = "0.4"
chrono-tz = "0.8"
clap = {version = "3.2.17", features = ["derive", "cargo"]}
console-subscriber = {version = "0.1.8", optional = true}
csrf = "0.4.1"
ctrlc = "3.2.2"
dhat = {version = "0.3.0", optional = true}
dotenv = "0.15.0"
futures = "0.3.21"
generational-arena = "0.2.8"
hex = "0.4.3"
html-escape = "0.2.11"
http = "0.2.8"
hyper = "0.14.20"
i18n-embed = {version = "0.13", features = ["fluent-system"]}
i18n-embed-fl = "0.6"
intercode_entities = {path = "./crates/intercode_entities"}
intercode_graphql = {path = "./crates/intercode_graphql"}
intercode_inflector = {path = "./crates/intercode_inflector"}
intercode_liquid = {path = "./crates/intercode_liquid"}
intercode_policies = {path = "./crates/intercode_policies"}
intercode_timespan = {path = "./crates/intercode_timespan"}
lazy_liquid_value_view = {path = "./crates/lazy_liquid_value_view"}
liquid = {workspace = true}
liquid-core = {workspace = true}
md5 = "*"
memo-map = "0.3.1"
once_cell = "1.13.0"
opentelemetry = {version = "0.18.0", features = ["rt-tokio"]}
opentelemetry-otlp = {version = "0.11.0", features = ["tls-roots"]}
oxide-auth = "0.5.3"
oxide-auth-axum = "0.2.0"
parking_lot = "0.12.1"
pulldown-cmark = "0.9.2"
quote = "1.0.20"
regex = "*"
rust-embed = "6"
rustls-pemfile = "1.0.1"
sea-orm = {version = "^0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}
seawater = {path = "./crates/seawater"}
serde = "1.0"
serde_json = "1.0"
sha1 = "0.10.5"
syn = "1.0.98"
time = "0.3.15"
tls-listener = {version = "0.5.1", features = ["rustls", "tokio-net"]}
tokio = {version = "~1.21", features = ["rt-multi-thread", "macros", "signal", "tracing"]}
tokio-rustls = "0.23.4"
tonic = "0.8.2"
tower = {version = "0.4.13", features = ["limit", "make"]}
tower-http = {version = "0.3.4", features = ["catch-panic", "compression-br", "compression-deflate", "compression-gzip", "trace"]}
tracing = "0.1.36"
tracing-flame = {version = "0.2.0", optional = true}
tracing-opentelemetry = "0.18.0"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
unic-langid = "0.9"
url = "*"
