//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0
#![allow(clippy::derive_partial_eq_without_eq)]

mod generated;
pub mod links;
mod maximum_event_signups_value;
pub use generated::*;

pub mod cms_parent;
pub mod model_ext;

pub use maximum_event_signups_value::MaximumEventSignupsValue;
pub use model_ext::UserNames;
