[package]
edition = "2021"
name = "intercode_policies"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
sea-orm = {version = "*", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}

[dependencies]
async-trait = "*"
axum = "*"
cached = "0.40.0"
futures = "*"
intercode_entities = {path = "../intercode_entities"}
oxide-auth = "*"
sea-orm = "*"
seawater = {path = "../seawater"}
tokio = {version = "*", features = ["rt-multi-thread", "macros"]}
tuple-conv = "1.0.1"
