[package]
edition = "2021"
name = "intercode_policies"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
axum = "*"
intercode_entities = {path = "../intercode_entities"}
memo-map = "*"
oxide-auth = "*"
oxide-auth-axum = "*"
sea-orm = "*"
tokio = "*"
