//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cms_files_pages")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub cms_file_id: i64,
  #[sea_orm(primary_key, auto_increment = false)]
  pub page_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cms_files::Entity",
    from = "Column::CmsFileId",
    to = "super::cms_files::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  CmsFiles,
  #[sea_orm(
    belongs_to = "super::pages::Entity",
    from = "Column::PageId",
    to = "super::pages::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Pages,
}

impl Related<super::cms_files::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CmsFiles.def()
  }
}

impl Related<super::pages::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Pages.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
