//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cms_partials")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub parent_id: Option<i32>,
  pub name: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub content: Option<String>,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
  pub parent_type: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub admin_notes: Option<String>,
  pub invariant: bool,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
