//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cms_variables")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub parent_id: Option<i64>,
  pub key: String,
  pub value: Option<Json>,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
  pub parent_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
