//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "coupon_applications")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub coupon_id: i64,
  pub order_id: i64,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::coupons::Entity",
    from = "Column::CouponId",
    to = "super::coupons::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Coupons,
  #[sea_orm(
    belongs_to = "super::orders::Entity",
    from = "Column::OrderId",
    to = "super::orders::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Orders,
}

impl Related<super::coupons::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Coupons.def()
  }
}

impl Related<super::orders::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Orders.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
