//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "signup_requests")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub state: String,
  pub user_con_profile_id: i64,
  pub target_run_id: i64,
  pub requested_bucket_key: Option<String>,
  pub replace_signup_id: Option<i64>,
  pub result_signup_id: Option<i64>,
  pub updated_by_id: Option<i64>,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::signups::Entity",
    from = "Column::ReplaceSignupId",
    to = "super::signups::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Signups2,
  #[sea_orm(
    belongs_to = "super::user_con_profiles::Entity",
    from = "Column::UserConProfileId",
    to = "super::user_con_profiles::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  UserConProfiles,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UpdatedById",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Users,
  #[sea_orm(
    belongs_to = "super::runs::Entity",
    from = "Column::TargetRunId",
    to = "super::runs::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Runs,
  #[sea_orm(
    belongs_to = "super::signups::Entity",
    from = "Column::ResultSignupId",
    to = "super::signups::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Signups1,
}

impl Related<super::user_con_profiles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserConProfiles.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl Related<super::runs::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Runs.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
