//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "staff_positions_user_con_profiles")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub staff_position_id: i64,
  #[sea_orm(primary_key, auto_increment = false)]
  pub user_con_profile_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
