//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tickets")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub user_con_profile_id: Option<i64>,
  pub ticket_type_id: Option<i64>,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
  pub provided_by_event_id: Option<i64>,
  pub order_entry_id: Option<i64>,
  pub run_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::runs::Entity",
    from = "Column::RunId",
    to = "super::runs::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Runs,
  #[sea_orm(
    belongs_to = "super::ticket_types::Entity",
    from = "Column::TicketTypeId",
    to = "super::ticket_types::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  TicketTypes,
  #[sea_orm(
    belongs_to = "super::events::Entity",
    from = "Column::ProvidedByEventId",
    to = "super::events::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Events,
  #[sea_orm(
    belongs_to = "super::order_entries::Entity",
    from = "Column::OrderEntryId",
    to = "super::order_entries::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  OrderEntries,
  #[sea_orm(
    belongs_to = "super::user_con_profiles::Entity",
    from = "Column::UserConProfileId",
    to = "super::user_con_profiles::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  UserConProfiles,
}

impl Related<super::runs::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Runs.def()
  }
}

impl Related<super::ticket_types::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TicketTypes.def()
  }
}

impl Related<super::events::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Events.def()
  }
}

impl Related<super::order_entries::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrderEntries.def()
  }
}

impl Related<super::user_con_profiles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UserConProfiles.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
