[package]
edition = "2021"
name = "intercode_graphql"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = {version = "*", features = ["dataloader", "tracing", "chrono"]}
async-session = "3.0.0"
chrono = "*"
chrono-tz = "*"
html-escape = "*"
http = "0.2.8"
i18n-embed = "*"
i18n-embed-fl = "*"
intercode_entities = {path = "../intercode_entities"}
intercode_inflector = {path = "../intercode_inflector"}
intercode_liquid = {path = "../intercode_liquid"}
intercode_policies = {path = "../intercode_policies"}
liquid = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}
liquid-core = {git = "https://github.com/nbudin/liquid-rust.git", branch = "lax-nulls"}
md5 = "*"
once_cell = "*"
pulldown-cmark = "*"
regex = "*"
sea-orm = "*"
seawater = {path = "../seawater"}
serde = "*"
serde_json = "*"
tokio = "*"
url = "*"
