[package]
edition = "2021"
name = "intercode_graphql"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = {workspace = true, features = ["dataloader", "tracing", "chrono"]}
async-stripe = {workspace = true}
async-trait = {workspace = true}
chrono = {workspace = true}
chrono-tz = {workspace = true}
futures = {workspace = true}
html-escape = {workspace = true}
http = {workspace = true}
i18n-embed = {workspace = true}
i18n-embed-fl = {workspace = true}
intercode_entities = {path = "../intercode_entities"}
intercode_graphql_core = {path = "../intercode_graphql_core"}
intercode_graphql_loaders = {path = "../intercode_graphql_loaders"}
intercode_inflector = {path = "../intercode_inflector"}
intercode_liquid = {path = "../intercode_liquid"}
intercode_policies = {path = "../intercode_policies"}
intercode_query_builders = {path = "../intercode_query_builders"}
intercode_timespan = {path = "../intercode_timespan"}
itertools = {workspace = true}
liquid = {workspace = true}
liquid-core = {workspace = true}
mailparse = {workspace = true}
md5 = {workspace = true}
once_cell = {workspace = true}
pulldown-cmark = {workspace = true}
regex = {workspace = true}
rusty-money = {workspace = true}
sea-orm = {workspace = true}
seawater = {path = "../seawater"}
serde = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
url = {workspace = true}
