name: CI

on: [push]

jobs:
  test:
    name: Compare schema against Ruby Intercode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'schema.graphql'
          endpoint: 'https://raw.githubusercontent.com/neinteractiveliterature/intercode/main/schema.json'
