name: CI

on: [push]

jobs:
  test:
    name: Compare schema against Ruby Intercode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - run: npm install @graphql-tools/load @graphql-tools/url-loader @graphql-tools/graphql-file-loader @graphql-inspector/core
      - run: node graphql-schema-diff.js
