name: GraphQL schema compatibility check

on:
  push:
    branches:
      - main
      - schema-diff

jobs:
  test:
    name: Compare schema against Ruby Intercode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - run: npm install @graphql-tools/load @graphql-tools/url-loader @graphql-tools/graphql-file-loader @graphql-inspector/core
      - id: schema_diff
        run: |
          echo 'MARKDOWN<<EOF' >>$GITHUB_OUTPUT
          node graphql-schema-diff.js >>$GITHUB_OUTPUT
          echo 'EOF' >>$GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 83,
              body: ${{ steps.schema_diff.outputs.MARKDOWN }}
            })
